/* for hsqldb */

CREATE TABLE
    SETTINGS
    (
        ID INTEGER IDENTITY,
        KEY VARCHAR(250) NOT NULL,
        PARENT INTEGER,
        USER VARCHAR(250) NOT NULL,
        CONSTRAINT SYS_CT_52 UNIQUE(KEY,USER)
    )
    
CREATE TABLE
    SETTINGS_VALUES
    (
        SETTINGS_ID INTEGER NOT NULL,
        KEY VARCHAR(250) NOT NULL,
        VALUE VARCHAR(250),
        PRIMARY KEY(SETTINGS_ID,KEY),
        CONSTRAINT SYS_FK_48 FOREIGN KEY(SETTINGS_ID) REFERENCES SETTINGS(ID)
    )
